### ISSUE TITLE
怎么编译？

### ISSUE THREAD

**Issue by jiexuan** [zju3dv/eval-vislam#1]
你好，非常感谢你们的工作。请问下这个工程怎么编译？我新建build文件，用cmake ..编译，显示错误。我的cmake版本是3.5.1 ，是不是我的版本不对？
CMake Error at CMakeLists.txt:7 (target_compile_features):
  Cannot specify compile features for imported target "eigen3-dep".

CMake Error at CMakeLists.txt:8 (target_link_libraries):
  Cannot specify link libraries for target "eigen3-dep" which is not built by
  this project.

**Comment by ybbbbt** [comment]
您好，可以尝试将CMake升级到3.10及以上。
