### ISSUE TITLE
找不到eigen3-dep yaml-cpp.dep

### ISSUE THREAD

**Issue by qiqzhang** [zju3dv/eval-vislam#2]

**Comment by qiqzhang** [comment]
我在本地编译了eigen3和yam-cpp,请问这个怎么解决,您在什么环境编译过得呢?

**Comment by ybbbbt** [comment]
您好，请问您的[yaml-cpp](https://github.com/jbeder/yaml-cpp)有安装到系统吗？

**Comment by qiqzhang** [comment]
谢谢，已经解决了．在ｕｂｕｎｔｕ18.04下使用ＣＭａｋｅ最新版本，运行通过．
