### ISSUE TITLE
Problem about data collection on iphone

### ISSUE THREAD

**Issue by JiaoYanMoGu** [zju3dv/eval-vislam#3]
Could you please tell me that which app you're using for collecting  IMU and Camera data ? Because I want to collect some data by my own iphone but I could not find an app for it.

**Comment by ybbbbt** [comment]
Hi, we use [sensor-toolkit](https://github.com/itsuhane/sensors-toolkit) to collect IMU and camera data in iPhone. Remember to disable video compression in the code.

**Comment by JiaoYanMoGu** [comment]
Thanks
