### ISSUE TITLE
Parameters of rolling shutter camera

### ISSUE THREAD

**Issue by XiaoxingChen** [zju3dv/eval-vislam#4]
Hi, excellent dataset!
My question is that where I can find the rolling shutter parameters corresponding to the "rolling_shutter_tr: rolling shutter read out time" in VINS_Mono? So far the sensor.yaml under "camera" folder doesn't contain this parameter.

Thanks!

**Comment by ybbbbt** [comment]
Hi, XiaoxingChen. Currently, we don't have rolling shutter readout time calibration.
