### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by dexdley94** [zju3dv/eval-vislam#5]
Hi, seems to be some problem while trying to run the eval code, when i read the source code, it seems to be some directory issues. I am using the MY-SLAM examples.

你好, 操作代码时遇到一些问题, 请协助.

![image](https://user-images.githubusercontent.com/52805888/62924966-d6c56f80-bde3-11e9-9be6-6d039e4fc2af.png)

**Comment by ybbbbt** [comment]
Hi, `ismar-scoring.py`  is designed for ISMAR 2019 Dataset only(`Cx` and `Dx` dataset), and cannot be used by `Ax` or `Bx` dataset. For trajectory evaluation, you can directly use `bin/accuracy`, and it would also give you the normalized score.
By the way, in `ismar-scoring.py`, `gt_base_dir` means the directory to the whole dataset (e.g. something like `/media/dexter/1TB01/VISLAM-Dataset` in your case).
