### ISSUE TITLE
Calibration Parameters

### ISSUE THREAD

**Issue by GabHoo** [zju3dv/eval-vislam#9]
Hi there! 

First of all congratulations on your whole work (dataset included). I just came across it and seems huge!

I wanted to ask if your calibration parameters were available because I couldn't find them anywhere.
I am talking about camera intrinsic, gyro and acc noise and walk and the camera-IMU transformation. 
Since you guys probably performed a fine calibration on those two common smartphones, such infos could be beneficial for some of us.

Thanks!

**Comment by ybbbbt** [comment]
Hi, you can find it in the [dataset](http://www.zjucvg.net/eval-vislam/dataset/#download).
